version: '3.0'

services: 
  client:
    container_name: client
    build: 
      context: .
  
  nginx:
    build: 
      context: ./nginx
    ports: 
      - 3000:3000
    depends_on: 
      - client